// node {
//     def app

//     stage('Clone repository') {
//         /* Let's make sure we have the repository cloned to our workspace */

//         checkout scm
//     }

//     stage('Build image') {
//         /* This builds the actual image; synonymous to
//          * docker build on the command line */

//         app = docker.build("tejasdurge55/node-dice-jenkins")
//     }

//     stage('Test image') {
//         /* Ideally, we would run a test framework against our image.
//          * For this example, we're using a Volkswagen-type approach ;-) */

//         app.inside {
//             sh 'echo "Tests passed"'
//         }
//     }

//     stage('Push image') {
//         /* Finally, we'll push the image with two tags:
//          * First, the incremental build number from Jenkins
//          * Second, the 'latest' tag.
//          * Pushing multiple tags is cheap, as all the layers are reused. */
//         docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
//             app.push("${env.BUILD_NUMBER}")
//             app.push("latest")
//         }
//     }
// }

//---------------------------------------------------------------------------------------------------------------------------------------------------------------------
// pipeline {

//   environment {
//     dockerimagename = "tejasdurge55/dice-nodeapp-gitsync"
//     dockerImage = ""
//   }

//   agent any

//   stages {

//     stage('Checkout Source') {
//       steps {
//         git 'https://github.com/tejasdurge55/jenkins_docker_integration.git'
//       }
//     }

//     stage('Build image') {
//       steps{
//         script {
//           dockerImage = docker.build dockerimagename
//         }
//       }
//     }

//     stage('Pushing Image') {
//       environment {
//                registryCredential = 'docker-hub-credentials'
//            }
//       steps{
//         script {
//           docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
//             dockerImage.push("latest")
//           }
//         }
//       }
//     }

//     stage('Deploying container to Kubernetes') {
//       steps {
//         script {
//           kubernetesDeploy(configs: "deployment.yaml")
//         }
//       }
//     }

//   }

// }

//---------------------------------------------------------------------------------------------------------------------------------------------------------------------

pipeline {
    
    agent any 
    
    environment {
        // IMAGE_TAG = "${BUILD_NUMBER}"
        dockerimagename = "tejasdurge55/dice-nodeapp-gitsync"
        dockerImage = ""
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git 'https://github.com/tejasdurge55/jenkins_docker_integration.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    dockerImage = docker.build dockerimagename
                }
            }
        }

        stage('Push the artifacts'){
            environment {
               registryCredential = 'docker-hub-credentials'
            }
            steps{
                script {
                    docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
                    dockerImage.push("latest")
                    }
                }
            }
        }
        
        stage('Checkout kubernetes deployment files'){
           steps {
                git 'https://github.com/tejasdurge55/dice-game-git-sync-node.git'
                // git url: "ssh://git@github.com:tejasdurge55/jenkins_docker_integration.git",
                 //  credentialsId: 'anyuser'
           }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{

//withCredentials([usernamePassword(credentialsId: 'github-credentials', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                      //git config user.email tejas.y.durge@gmail.com
                       //git config user.name tejasdurge55
                     //git clone https://github.com/tejasdurge55/dice-game-git-sync-node.git
                        sh '''
                       
                        cd /tejas-git/dice-game-git-sync-node/argo-cd-folder
                        cat deployment.yaml                     
                        current_number=$(head -n 1 deployment.yaml | sed 's/#//')             
                        new_number=$((current_number + 1))  
                        cp deployment.yaml /tmp
                        sed -i -e "1s/.*/#$new_number/" /tmp/deployment.yaml
                        cat /tmp/deployment.yaml >/tejas-git/dice-game-git-sync-node/argo-cd-folder/                  
                                        
                        cat deployment.yaml
                        git add deployment.yaml
                        git commit -m 'Updated the deployment yaml | Jenkins Pipeline'
                       
                       git push
                         ''' 
//}
                }
            }
        }
    }
}
